version: "3"

services:
  nginx-proxy:
    image: jwilder/nginx-proxy
    container_name: nginx-proxy
    networks:
      - proxy-network
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
      - /var/certs:/etc/nginx/certs
    ports:
      - "80:80"
      - "443:443"

  download:
    image: nginx
    container_name: download
    networks:
      - proxy-network
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - /var/download:/usr/share/nginx/html
    environment:
      - VIRTUAL_HOST=download.${DOMAIN}
      - HTTPS_METHOD=noredirect

networks:
  proxy-network:
    external:
      name: proxy-network
