version: "3"

services:
  ssh:
    image: nginx
    container_name: ssh
    networks:
      - proxy-network
    ports:
      - ${SSHPORT}:${SSHPORT}
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro

networks:
  proxy-network:
    external:
      name: proxy-network
