version: "3"

services:
  hub:
    image: registry:2
    container_name: hub
    networks:
      - proxy-network
    volumes:
      - ./auth:/auth
      - /var/certs:/certs
    environment:
      VIRTUAL_PORT: 443
      VIRTUAL_PROTO: https
      VIRTUAL_HOST: hub.${DOMAIN}
      REGISTRY_AUTH: htpasswd
      REGISTRY_AUTH_HTPASSWD_REALM: "Registry Realm"
      REGISTRY_AUTH_HTPASSWD_PATH: /auth/htpasswd
      REGISTRY_HTTP_TLS_CERTIFICATE: /certs/hub.${DOMAIN}.crt
      REGISTRY_HTTP_TLS_KEY: /certs/hub.${DOMAIN}.key

networks:
  proxy-network:
    external:
      name: proxy-network
