version: "3"

services:
  nodeapp:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: nodeapp
    networks:
      - proxy-network
    environment:
      - VIRTUAL_HOST=nodeapp.${DOMAIN}

networks:
  proxy-network:
    external:
      name: proxy-network
